# Generated by Django 5.0 on 2024-01-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShipprMore',
            new_name='ShipperMore',
        ),
    ]
