# Generated by Django 5.0 on 2024-01-18 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vehicel',
            new_name='vehicle',
        ),
    ]
