# Generated by Django 5.0 on 2024-01-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_shipprmore_shippermore'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippermore',
            name='vehicle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BASIC_USER', 'Basic user'), ('SHIPPER', 'Shipper')], default='BASIC_USER', max_length=50),
        ),
        migrations.DeleteModel(
            name='VehicleShipper',
        ),
    ]
