# Generated by Django 5.0 on 2024-01-22 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shippermore_vehicle_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippermore',
            name='vehicle_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippermore',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vehicle'),
        ),
    ]
