# Generated by Django 5.0 on 2024-01-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shippermore_vehicle_number_alter_shippermore_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BASIC_USER', 'Basic user'), ('SHIPPER', 'Shipper')], default='ADMIN', max_length=50),
        ),
    ]
