# Generated by Django 5.0 on 2023-12-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
