# Generated by Django 5.0 on 2023-12-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_job_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_job', to='core.job'),
        ),
    ]
