# Generated by Django 5.0 on 2023-12-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='collect_on',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivered_on',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='ready_on',
        ),
        migrations.AddField(
            model_name='shipment',
            name='expected_delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_date',
            field=models.DateField(null=True),
        ),
    ]
