# Generated by Django 5.0 on 2023-12-19 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_shipment_collect_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_shipper', to=settings.AUTH_USER_MODEL),
        ),
    ]
