# Generated by Django 5.0 on 2023-12-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_auction_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='shipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_shipper', to='core.shipper'),
        ),
    ]
