# Generated by Django 5.0 on 2024-01-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_auction_shipper'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicelShipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicel_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='shipper',
            name='cmnd',
            field=models.ImageField(null=True, upload_to='shipper/%Y/%m'),
        ),
        migrations.AddField(
            model_name='vehicelshipper',
            name='shipper',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.shipper'),
        ),
        migrations.AddField(
            model_name='vehicelshipper',
            name='vehicel_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.vehiceltype'),
        ),
    ]
