# Generated by Django 5.0 on 2024-01-17 05:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vehicelshipper_vehiceltype_delete_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='cmnd',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
