# Generated by Django 5.0 on 2024-01-17 05:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_shipper_cmnd_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='cmnd',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cmnd'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
    ]
