# Generated by Django 5.0 on 2024-01-17 13:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_shipper_cmnd_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='shipper',
            name='cmnd',
            field=models.CharField(max_length=12),
        ),
        migrations.DeleteModel(
            name='VehicelShipper',
        ),
        migrations.DeleteModel(
            name='VehicelType',
        ),
    ]
