# Generated by Django 5.0 on 2024-01-17 14:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_photo_alter_shipper_cmnd_delete_vehicelshipper_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='cmnd',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cmnd'),
        ),
    ]
