# Generated by Django 5.0 on 2024-01-17 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_shipper_cmnd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VehicelShipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicel_nummber', models.CharField(max_length=20)),
                ('shipper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.shipper')),
                ('vehicel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.vehicel')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
