# Generated by Django 5.0 on 2024-01-18 13:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_vehicel_vehicelshipper_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='cmnd',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='cmnd'),
        ),
    ]
